### ISSUE TITLE
STAR for ExPose

### ISSUE THREAD

**Issue by alexisrolland** [ahmedosman/STAR#6]
Hello @ahmedosman and thank you for opening STAR source code! Can it be used in combination with ExPose?

https://github.com/vchoutas/expose

**Comment by ahmedosman** [comment]
Hi @alexisrolland  Expose was trained for SMPL-X, since the pose and shape space of STAR are different, we can not plug in the parameters of SMPL-X in STAR. However, I'll release shortly a convertor script to convert SMPL-X parameters to STAR parameters. So the flow would be, use expose to regress SMPL-X parameters, convert the SMPL-X parameters to STAR.

**Comment by alexisrolland** [comment]
Thank you @ahmedosman for your quick answer!
It would be great to have an update on this question once you are done with this task.
Thanks again for your hard work on STAR.

**Comment by ahmedosman** [comment]
@alexisrolland  

Here is the script to convert smplx to star.  https://github.com/ahmedosman/STAR/blob/master/convertors/convert_smplx_to_star.py

It reads smplx (vertices) from disk and fit STAR and dumps the STAR vertices and parameters. 

I'll close this issue now.
